# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image
FROM node:18-alpine AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY . .

# Build the project
RUN npm run build

# Use a separate image for the runtime
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the previous stage
COPY --from=build /app/dist /app/dist
COPY --from=build /app/package.json /app/package.json

# Install only production dependencies
RUN npm ci --omit=dev

# The environment variable for the Notion integration token
ENV NOTION_INTEGRATION_TOKEN=your-notion-token-here

# Start the server
CMD ["node", "dist/index.js", "-t", "$NOTION_INTEGRATION_TOKEN"]
